"""initial schema

Revision ID: bb06dbacc4a3
Revises: 
Create Date: 2026-09-18 10:38:37.574463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb06dbacc4a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.Enum('SINGLE_CHOICE', 'MULTI_CHOICE', 'OPEN_TEXT', 'MATRIX_SINGLE_CHOICE', name='answer_type_enum'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Numeric(), nullable=True),
    sa.Column('elevation_gain_m', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Numeric(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MODERATE', 'HARD', 'EXPERT', name='difficulty_level_enum'), nullable=True),
    sa.Column('terrain_steep_stairs', sa.Boolean(), nullable=False),
    sa.Column('terrain_slippery', sa.Boolean(), nullable=False),
    sa.Column('terrain_rope_scramble', sa.Boolean(), nullable=False),
    sa.Column('terrain_exposed_ridge', sa.Boolean(), nullable=False),
    sa.Column('terrain_unclear_trail', sa.Boolean(), nullable=False),
    sa.Column('no_signal_area', sa.Boolean(), nullable=False),
    sa.Column('open_status', sa.Enum('OPEN', 'CLOSED', 'PARTIAL_CLOSED', name='open_status_enum'), nullable=False),
    sa.Column('open_status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('questionnaire_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaire_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('has_matches', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiking_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiking_plan_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hiking_plan_id', sa.Integer(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.Enum('ROUTE_SUMMARY', 'ITINERARY', 'WEATHER_CONDITIONS', 'RISK_RESPONSE', 'GEAR_SUPPLY', 'TRANSPORTATION', 'EMERGENCY_RESPONSE', 'PRE_TRIP_CHECKLIST', name='section_name_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hiking_plan_id'], ['hiking_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hiking_plan_section')
    op.drop_table('recommendation_route')
    op.drop_table('hiking_plan')
    op.drop_table('recommendation')
    op.drop_table('questionnaire_answer')
    op.drop_table('user')
    op.drop_table('route')
    op.drop_table('questionnaire_question')
    # ### end Alembic commands ###
